{
 "title": "Demo",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Ready Pods",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_ready{deployment=\"demo\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget remaining",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (demo:error_ratio:rate6h / 0.005))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p95 latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"demo\"}[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "100 * demo:error_ratio:rate5m", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"demo\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}